# Abstract

En este proyecto se ha desarrollado un modelo predictivo capaz de estimar la probabilidad de que un paciente presente enfermedad cardiovascular, a partir de un conjunto de variables clínicas y demográficas extraídas de un dataset proporcionado por una clínica. Se ha llevado a cabo un análisis exploratorio detallado de las variables, identificando su tipología y su relación con la variable de estudio. Posteriormente, se han implementado y comparado distintos modelos de predicción, incluyendo técnicas de aprendizaje automático y aprendizaje profundo, cuya validez se ha evaluado mediante un esquema de validación cruzada 5×2. Finalmente, el modelo con mejor rendimiento ha sido desplegado en forma de una aplicación web, permitiendo su uso para la predicción con nuevos datos clínicos.

# Introducción

Las enfermedades cardiovasculares (ECV) constituyen la principal causa de mortalidad en el mundo, según [@OPS_ECV]. Más de tres cuartas partes de las muertes por ECV se producen en países de ingresos medios y bajos, donde los factores de riesgo como la mala alimentación, el sedentarismo y el consumo de tabaco están especialmente presentes. En España, la situación no es muy diferente: se registran anualmente más de 125.000 muertes y más de cinco millones de estancias hospitalarias debido a ECV, lo que convierte a estas enfermedades en la primera causa de muerte y hospitalización en el país. [@BANEGAS20063G]

Muchos pacientes en riesgo no presentan síntomas evidentes y más del 60% no controla adecuadamente los factores de riesgo. Además, más de un tercio de los infartos agudos de miocardio terminan en muerte antes de llegar al hospital, evidenciando que, en esos casos, la prevención ha llegado demasiado tarde. Esto no solo representa una carga clínica y emocional, sino también un desafío económico para el sistema sanitario, que difícilmente podrá sostener este ritmo de atención en el futuro. Por tanto, es urgente redoblar los esfuerzos en prevención primaria, anticipando el riesgo antes de que la enfermedad se manifieste.

En este contexto, se presenta este proyecto, cuyo objetivo principal es desarrollar un modelo predictivo capaz de estimar la probabilidad de que un paciente padezca enfermedad cardiovascular a partir de datos clínicos y demográficos. Para ello, se ha utilizado un conjunto de datos que recoge variables relevantes como edad, sexo, tipo de dolor torácico, presión arterial en reposo, colesterol, glucosa en ayunas, electrocardiograma en reposo, frecuencia cardíaca máxima, presencia de angina inducida por ejercicio, descenso del segmento ST, pendiente del ST, y un indicador final de presencia de enfermedad.

Este modelo, una vez entrenado y validado mediante técnicas robustas como la validación cruzada 5x2, no solo permite estimar el riesgo de forma precisa, sino que también se ha integrado en una aplicación web interactiva, facilitando así su uso en entornos clínicos reales para apoyar la toma de decisiones médicas en tareas de prevención.

# Sobre el autor

<div>

<p>Hola soy <strong>Alberto Montero</strong> estudiante en Bioinformática y Ciencia de Datos Clínicos. Esto se trata de un proyecto realizado para la asignatura de <strong>Minería de Datos</strong> en la <strong>Universidad de Málaga</strong>.</p>

<p>Puede contactarme a través de cualquiera de mis redes sociales.</p>

::: social-icons
<a href="https://github.com/monteero13" target="_blank" aria-label="GitHub"> <svg class="icon" viewBox="0 0 24 24"> <path d="M12 0.5C5.37 0.5 0 5.87 0 12.5c0 5.29 3.44 9.77 8.21 11.37.6.11.82-.26.82-.58v-2.01c-3.34.73-4.04-1.61-4.04-1.61-.55-1.41-1.34-1.79-1.34-1.79-1.1-.75.08-.74.08-.74 1.21.08 1.85 1.25 1.85 1.25 1.08 1.85 2.83 1.31 3.52 1 .11-.78.42-1.31.76-1.61-2.67-.3-5.47-1.34-5.47-5.95 0-1.31.47-2.38 1.24-3.22-.12-.3-.54-1.52.12-3.18 0 0 1.01-.32 3.3 1.23a11.5 11.5 0 0 1 6 0c2.29-1.55 3.3-1.23 3.3-1.23.66 1.66.24 2.88.12 3.18.77.84 1.24 1.91 1.24 3.22 0 4.62-2.81 5.65-5.49 5.95.43.37.82 1.1.82 2.22v3.29c0 .32.21.7.83.58A12.5 12.5 0 0 0 24 12.5C24 5.87 18.63 0.5 12 0.5z"/> </svg> </a><a href="https://www.instagram.com/albeertomontero_" target="_blank" aria-label="Instagram"> <svg class="icon" viewBox="0 0 24 24"> <path d="M12 2.2c3.2 0 3.6 0 4.9.1 1.2.1 2 .2 2.5.4a5 5 0 0 1 1.8 1.1c.5.5.9 1.1 1.1 1.8.2.5.3 1.3.4 2.5.1 1.3.1 1.7.1 4.9s0 3.6-.1 4.9c-.1 1.2-.2 2-.4 2.5a5 5 0 0 1-1.1 1.8c-.5.5-1.1.9-1.8 1.1-.5.2-1.3.3-2.5.4-1.3.1-1.7.1-4.9.1s-3.6 0-4.9-.1c-1.2-.1-2-.2-2.5-.4a5 5 0 0 1-1.8-1.1 5 5 0 0 1-1.1-1.8c-.2-.5-.3-1.3-.4-2.5C2.2 15.6 2.2 15.2 2.2 12s0-3.6.1-4.9c.1-1.2.2-2 .4-2.5a5 5 0 0 1 1.1-1.8 5 5 0 0 1 1.8-1.1c.5-.2 1.3-.3 2.5-.4C8.4 2.2 8.8 2.2 12 2.2zm0-2.2C8.7 0 8.3 0 7 .1 5.6.2 4.4.5 3.4 1A7.2 7.2 0 0 0 1 3.4c-.5 1-0.8 2.2-1 3.6C0 8.3 0 8.7 0 12s0 3.7.1 5c.2 1.4.5 2.6 1 3.6a7.2 7.2 0 0 0 2.4 2.4c1 .5 2.2.8 3.6 1 1.3.1 1.7.1 5 .1s3.7 0 5-.1c1.4-.2 2.6-.5 3.6-1a7.2 7.2 0 0 0 2.4-2.4c.5-1 .8-2.2 1-3.6.1-1.3.1-1.7.1-5s0-3.7-.1-5c-.2-1.4-.5-2.6-1-3.6a7.2 7.2 0 0 0-2.4-2.4c-1-.5-2.2-.8-3.6-1C15.7 0 15.3 0 12 0zM12 5.8a6.2 6.2 0 1 0 0 12.4A6.2 6.2 0 0 0 12 5.8zm0 10.2a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm6.4-11.8a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/> </svg> </a><a href="https://www.linkedin.com/in/alberto-montero-solera-29a0a32a2" target="_blank" aria-label="LinkedIn"> <svg class="icon" viewBox="0 0 24 24"> <path d="M4.98 3.5C4.98 5 3.9 6 2.5 6S0 5 0 3.5 1.07 1 2.5 1s2.48 1.07 2.48 2.5zM.5 8h4V24h-4V8zm7.5 0h3.8v2.2h.1c.5-1 1.9-2.2 4-2.2 4.2 0 5 2.6 5 6v9h-4v-8c0-2 0-4.5-2.8-4.5-2.8 0-3.2 2.1-3.2 4.3v8.2h-4V8z"/> </svg> </a>
:::

</div>
